const testData={sections:[
{title:'Section 1 — Community Centre',questions:[
['short','What time does the centre open on Saturdays?','9:30'],['short','How much is the photography course?','45'],['short','Where will the first meeting take place?','Room 4'],['short','What kind of notebook should participants bring?','A4'],['mcq','Why has the event been moved indoors?',['Bad weather','Road repairs','A power cut'],'Bad weather'],['short','What time will the guest speaker arrive?','10:15'],['short','What should visitors buy first?','A ticket'],['short','Which street has the nearest bus stop?','King Street'],['short','Which facility was recently renovated?','The library'],['short','What must new members show at reception?','ID'] ]},
{title:'Section 2 — City Library Tour',questions:[
['mcq','Which floor has the children’s library?',['Ground floor','First floor','Second floor'],'First floor'],['short','How many computers are available in the study area?','24'],['short','What day is the writing club held?','Thursday'],['short','What is the maximum loan period for magazines?','7 days'],['mcq','What is the quietest area?',['Reading room','Café','Entrance hall'],'Reading room'],['short','Where can visitors print documents?','The help desk'],['short','What colour are the library lockers?','Blue'],['short','When does the evening study session finish?','8 pm'],['mcq','What does the library offer free of charge?',['Coffee','Wi-Fi','Stationery'],'Wi-Fi'],['short','What should visitors do with bags?','Use the lockers'] ]},
{title:'Section 3 — Student Project Discussion',questions:[
['short','What is the students’ project topic?','Urban gardens'],['mcq','Who will design the questionnaire?',['Maya','Daniel','Sara'],'Maya'],['short','How many people do they plan to interview?','30'],['short','Which age group is the main focus?','Teenagers'],['mcq','What problem did their teacher identify?',['Too few sources','An unclear aim','A long introduction'],'An unclear aim'],['short','When will the students collect data?','Friday'],['short','Where will they meet afterwards?','The café'],['mcq','Which graph will they use?',['Pie chart','Line graph','Map'],'Pie chart'],['short','Who will check the final references?','Daniel'],['short','What is the presentation date?','18 May'] ]},
{title:'Section 4 — Technology and Learning',questions:[
['mcq','What is the main advantage of adaptive learning software?',['It changes lessons to suit learners','It removes teachers','It works without internet'],'It changes lessons to suit learners'],['short','What does the system analyse first?','Learning behaviour'],['short','How often should students review difficult words?','Daily'],['mcq','Which skill can technology practise particularly well?',['Pronunciation','Handwriting','Drawing'],'Pronunciation'],['short','What should teachers still provide?','Feedback'],['short','What can cause inaccurate progress data?','Irregular use'],['mcq','What is recommended for group activities?',['Face-to-face discussion','Silent reading','Individual tests'],'Face-to-face discussion'],['short','How long should a focused study session last?','25 minutes'],['short','What should students turn off during study?','Notifications'],['mcq','What is the final message of the lecture?',['Technology should support learning','Technology should replace schools','Technology is only for entertainment'],'Technology should support learning'] ]}
]};
const script=`Section 1. Welcome to the community centre. On Saturdays the centre opens at nine thirty. The photography course costs forty-five pounds. The first meeting is in Room 4, and participants should bring an A4 notebook. Because of bad weather, the event has been moved indoors. The guest speaker arrives at ten fifteen. Visitors should buy a ticket first. The nearest bus stop is on King Street. The library was recently renovated. New members must show ID at reception.
Section 2. The children’s library is on the first floor. There are twenty-four computers in the study area. The writing club meets on Thursday. Magazines can be borrowed for seven days. The reading room is the quietest area. Documents can be printed at the help desk. The lockers are blue. The evening study session finishes at eight pm. Wi-Fi is free. Bags should be placed in the lockers.
Section 3. The students are preparing a project about urban gardens. Maya will design the questionnaire. They plan to interview thirty people, focusing on teenagers. Their teacher said the project has an unclear aim. They will collect data on Friday and meet afterwards at the café. They will use a pie chart. Daniel will check the final references. The presentation is on 18 May.
Section 4. Adaptive learning software can change lessons to suit individual learners. The system first analyses learning behaviour. Students should review difficult words daily. Technology can practise pronunciation particularly well. Teachers still need to provide feedback. Irregular use can make progress data inaccurate. Group activities are best supported by face-to-face discussion. A focused study session should last about twenty-five minutes. Students should turn off notifications. The final message is that technology should support learning, not replace learning itself.`;
